export const UPDATE = "UPDATE"
export const FETCH_ALL = "FETCH_ALL"
export const CREATE = "CREATE"
export const DELETE = "DELETE"
export const UPDATE_LIKE = "UPDATE_LIKE"
export const AUTH = "AUTH"
export const LOGOUT = "LOGOUT"
export const FETCH_BY_SEARCH = "FETCH_BY_SEARCH"
